{% set name = "google-resumable-media" %}
{% set version = "2.7.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eae451a7b2e2cdbaaa0fd2eb00cc8a1ee5e95e16b55597359cbc3d27d7d90e33

build:
  number: 0
  skip: True  # [py<37]
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - google-crc32c >=1.0,<2.0dev
  run_constrained:
    - requests >=2.18.0,<3.0.0dev
    - aiohttp >=3.6.2,<4.0.0dev
    # Commenting google-auth <2 upper bound to not block google-cloud-storage, which depends on google-auth>=2.26.1
    # Related: https://github.com/googleapis/google-resumable-media-python/issues/417
    #- google-auth >=1.22.0,< 2.0dev
    - google-auth >=1.22.0

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.resumable_media
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/google-resumable-media-python
  summary: Utilities for Google Media Downloads and Resumable Uploads
  description: Utilities for Google Media Downloads and Resumable Uploads
  doc_url: https://cloud.google.com/python/docs/reference/google-resumable-media/latest
  dev_url: https://github.com/googleapis/google-resumable-media-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johanneskoester
    - leahecole
    - parthea
    - tswast
  skip-lints:
    - missing_doc_source_url
    - invalid_url