{% set version = "0.3.3" %}

package:
  name: google-resumable-media
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/google-resumable-media/google-resumable-media-{{ version }}.tar.gz
  sha256: 49493999cf046b5a02f648e201f0c2fc718c5969c53326b4d2c0693b01bdc8bb

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - google
    - google.resumable_media

about:
  home: https://github.com/GoogleCloudPlatform/google-resumable-media-python
  summary: Utilities for Google Media Downloads and Resumable Uploads
  doc_url: https://googlecloudplatform.github.io/google-resumable-media-python
  dev_url: https://github.com/GoogleCloudPlatform/google-resumable-media-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johanneskoester
    - parthea
    - tswast
