{% set version = "0.3.2" %}

package:
  name: google-resumable-media
  version: {{ version }}

source:
  fn: google-resumable-media-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/google-resumable-media/google-resumable-media-{{ version }}.tar.gz
  sha256: 3e38923493ca0d7de0ad91c31acfefc393c78586db89364e91cb4f11990e51ba

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six

test:
  imports:
    - google
    - google.resumable_media

about:
  home: https://github.com/GoogleCloudPlatform/google-resumable-media-python
  summary: Utilities for Google Media Downloads and Resumable Uploads
  doc_url: https://googlecloudplatform.github.io/google-resumable-media-python
  dev_url: https://github.com/GoogleCloudPlatform/google-resumable-media-python
  license: Apache-2.0
  license_family: APACHE
  license_file: {{ RECIPE_DIR }}/LICENSE

extra:
  recipe-maintainers:
    - johanneskoester
    - parthea
    - tswast
