{% set version = "2.0.3" %}

package:
  name: google-resumable-media
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/google-resumable-media/google-resumable-media-{{ version }}.tar.gz
  sha256: b4b4709d04a6a03cbec746c2b5cb18f1f9878bf1ef3cd61908842a3d94c20471

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6
    - six >=1.4.0
    - google-crc32c >=1.0,<2.0dev  # [py>=35]
  run_constrained:
    - requests >=2.18.0,<3.0.0dev
    - aiohttp >=3.6.2,<4.0.0dev  # [py>=36]

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.resumable_media
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/google-resumable-media-python
  summary: Utilities for Google Media Downloads and Resumable Uploads
  doc_url: https://googleapis.github.io/google-resumable-media-python/latest/
  dev_url: https://github.com/googleapis/google-resumable-media-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johanneskoester
    - leahecole
    - parthea
    - tswast
