{% set version = "0.4.1" %}

package:
  name: google-resumable-media
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/google-resumable-media/google-resumable-media-{{ version }}.tar.gz
  sha256: cdeb8fbb3551a665db921023603af2f0d6ac59ad8b48259cb510b8799505775f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
  run_constrained:
    - requests >=2.18.0,<3.0.0dev

test:
  imports:
    - google
    - google.resumable_media

about:
  home: https://github.com/GoogleCloudPlatform/google-resumable-media-python
  summary: Utilities for Google Media Downloads and Resumable Uploads
  doc_url: https://googlecloudplatform.github.io/google-resumable-media-python
  dev_url: https://github.com/GoogleCloudPlatform/google-resumable-media-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johanneskoester
    - parthea
    - tswast
