travis:
  secure:
    BINSTAR_TOKEN: 5oANoGsZpO9gVSE2Dy5dUQvFmKmMvT1cRCoaIFAXF0QdOj1bPE7xTDllEWj5sCxoTzX21CZijtLOPkVYmQYH/b3ZJWEdd07/05RYgZFsBhx2rILhmN+KOju9PeOQ/z7G0UF4ZjPaK3vjNonJYgaLK3nfybveAUwQIZIiS+/cXt+2qA3Y5RwyjEnkHKXKCRx4hLC2v5d4crg7LTwF0E0HlC7ZE0EJp6Bi4/+BbAfGkYKd0rcCoRngUEHbuQiEKswhP8oE8LehHne430eABhkobTSJKFvAJ1+YRaKzg3sNH63anbzKftC1m7Z5f0z/utTwSI6UVGFc+2c1O+hC5kwXntzgvyFACdLgDKDv+9fdZKI2oa72ljSsHdAxGNwePKm/nOeOcNZWEKprJPRPprj+FS2zDbPfJrBgytJvHlgDNk51Jw2U/jbP/9S56TaIaPho1PCoJBHj5SVdOh7ARw/flpKmWWOFNoauoiq2V1j6I7XEsY81MoMLjlC3sYrVTlWRhszDiDvbKwd/aSEqX6jYDmb081iGKtTAbrh1RGMd/aD88ZJ+ufhRF2yRQKdAVGQUQRyKMF25EgxdBFtBb+UitjJ8irob1gcNic/Xyzo/LTgoNryCq9KbuN6HXq5iFcxKLCRwf7OIAXo94H7Hn5gVqViPeBfgL8bJc6/iSlKokLE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
